name: CI Windows

on:
  pull_request:
    paths-ignore:
      - 'microsite/**'
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v2
      - name: fetch branch master
        run: git fetch origin master

      # Beginning of yarn setup, keep in sync between all workflows, see ci.yml
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: find location of global yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache global yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install --frozen-lockfile
      # End of yarn setup

      - name: check for yarn.lock changes
        id: yarn-lock
        run: git diff --quiet origin/master HEAD -- yarn.lock

      - name: lint
        run: yarn lerna -- run lint

      - name: test
        run: yarn lerna -- run test

      - name: test changed packages
        if: ${{ steps.yarn-lock.outcome == 'success' }}
        run: yarn lerna -- run test --since origin/master -- --coverage

      - name: test all packages (and upload coverage)
        if: ${{ steps.yarn-lock.outcome == 'failure' }}
        run: |
          yarn lerna -- run test -- --coverage
          bash <(curl -s https://codecov.io/bash) -N $(git rev-parse FETCH_HEAD)
